base_url = "https://phisch.dev"
title = "phisch.dev"
description = "Programming, designing and exploring interesting stuff."
default_language = "en"

compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true
author = "Philipp Schaffrath"

taxonomies = [
    { name = "projects", feed = true, render = false },
    { name = "tags", feed = true, render = false },
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "phocus"

[extra]
sld = "phisch"
tld = "dev"

navigation = [
    { title = "Blog", target = "_index.md" }
]

[extra.author]
name = "Philipp Schaffrath"
email = "philipp.schaffrath@gmail.com"
gpg = "6BEB 117F 7BDB D749"
#gpg = "A001 55F3 C961 D57E 6452 99D6 6BEB 117F 7BDB D749"

socials = [
    { name = "GitHub", icon = "github", handle = "phisch", url = "https://github.com/phisch", header = true },
    { name = "Libera.chat", icon = "tag", handle = "phisch", note = "on libera.chat" },
    { name = "Matrix", icon = "matrix", handle = "@phisch:matrix.org", url = "https://matrix.to/#/@phisch:matrix.org" },
    { name = "Discord", icon = "discord", handle = "phisch.dev" },
    { name = "X", icon = "twitter", handle = "phischdev", url = "https://x.com/phischdev" },
    { name = "Mastodon", icon = "mastodon", handle = "@phisch@fosstodon.org", url = "https://fosstodon.org/@phisch" },
    { name = "Keybase", icon = "keybase", handle = "phisch", url = "https://keybase.io/phisch" },
    { name = "Email", icon = "email", handle = "philipp.schaffrath@gmail.com", url = "mailto:philipp.schaffrath@gmail.com" }
]

[extra.giscus]
repo = "phisch/phisch.dev"
repo_id = "R_kgDOI3LDOw"
category = "Comments"
category_id = "DIC_kwDOI3LDO84CfsA8"
mapping = "pathname"
strict = true
input_position = "bottom"
reactions_enabled = false
emit_metadata = false
lang = "en"